spring:
  datasource:
    url: jdbc:mariadb://localhost:3106/school?useSSL=false
    username: root
    password: 123mudar
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8090
